### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by ainterr** [ainterr/scoring_engine#1]
Getting IMAP and POP3 to work requires python 3. We should port the whole Django app to python 3 since it's much easier to [translate modules from 2 to 3](http://python-future.org/translation.html) than the other way around - the process is documented [here](https://docs.djangoproject.com/en/1.9/topics/python3/).

**Comment by resetcentral** [comment]
I've ported the scoring engine to python3. It seems to work on a surface level. I'm not too familiar with the internals. Feel free to close this ticket if you think it's working.
